[build]
  base = "website"
  command = "npm run build"
  publish = "build"

[context.production]
  ignore = "node -e 'process.exit(0)'"

[context.branch-deploy]
  ignore = "node -e 'process.exit(0)'"
